include_guard()

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_CROSSCOMPILING ON)

if(GX_TOOLHAIN_TARGET_NAME STREQUAL  "SOPHON" )
    set(CMAKE_C_COMPILER ${GX_TOOLCHAIN_PREFIX}gcc-11.4.0)
else()
    set(CMAKE_C_COMPILER ${GX_TOOLCHAIN_PREFIX}gcc)
endif()
set(CMAKE_CXX_COMPILER ${GX_TOOLCHAIN_PREFIX}g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
